[build]
  command = "npm run build"
  publish = "dist/my-angular-app" # Replace 'my-angular-app' with the correct path to your Angular app's build output.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
